version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - "bassetts"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - "bassetts"
