name: docker

on:
  release:
    types:
      - published

jobs:
  docker-build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get the release version
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Get short release version
        id: get_short_version
        run: |
          tag_name="${{ steps.get_version.outputs.version }}"
          version_parts=(${tag_name//./ })
          short_version="${version_parts[0]}"."${version_parts[1]}"
          echo "::set-output name=version::$short_version"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bassetts/warp-cors
          tags: >-
            ${{ steps.get_version.outputs.version }},
            ${{ steps.get_short_version.outputs.version }},
            latest
